version: '2.0'
services:
  app:
    build: .
    depends_on:
      - loki
      - grafana
  grafana:
    build: grafana/
    ports:
      - '3000:3000'
    depends_on:
      - loki
  loki:
    build: loki/
    ports:
      - '3100:3100'
